#!/bin/env python
#
#   mksketch
#
#   This is a program to make a C "sketch" file from an SVG image
#   Copyright (C) 2006  Douglas P. Lau
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   included COPYING file for more details.
#
import sys
from svgclean.sketcher import make_sketch

make_sketch(sys.argv[1])
