#!/bin/env python
#
#   svg2pixy
#
#   This is a program to make a pixy file from an SVG image
#   Copyright (C) 2013  Douglas P. Lau
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   included COPYING file for more details.
#
from os.path import splitext
import sys
from svgclean.pixy import make_pixy

if len(sys.argv) != 2:
	print('Usage %s [svg-file]' % sys.argv[0])
	sys.exit(1)

iname = sys.argv[1]
if sys.stdout.isatty():
	oname = splitext(iname)[0] + '.pixy'
	out = open(oname, 'wb')
else:
	out = sys.stdout
make_pixy(open(iname), out)
